### ISSUE TITLE
 CUDA and cuDNN versions

### ISSUE THREAD

**Issue by sighdn** [liusiqinqinqin/probabilistic-model-based-change-detection#2]
I really appreciate the method provided by yours, I wanted to use your code as a comparative algorithm.I am using CUDA version 11.7 and cuDNN version 8.X. I encountered the following error
![image](https://github.com/liusiqinqinqin/probabilistic-model-based-change-detection/assets/140034622/9bbeda41-4a35-4f2c-b850-55c63b9629fb)

**Comment by liusiqinqinqin** [comment]
CUDNN has changed the getalgorithm functions in new versions. You can directly define the algorithm, for example, "cudnnConvolutionFwdAlgo_t alg = CUDNN_CONVOLUTION_FWD_ALGO_IMPLICIT_GEMM;". More details about the algorithms are carefully described in the cuDNN-API attached below.
        
            
        
    
         
        
            
                        
            
        
     
        
  
    ---- Replied Message ----
  
  
    
      
        
         From 
        
        
            ***@***.***>
            
        
      
      
        
         Date 
        
        
        7/22/2023 18:29
        
      
      
        
         To 
        
        
         
          
            ***@***.***>
            
          
        
      
      
        
         Cc 
        
        
          
            ***@***.***>
            
          
        
      
      
        
         Subject 
        
        
              [liusiqinqinqin/probabilistic-model-based-change-detection] CUDA and cuDNN versions (Issue #2)
        
      
    
  

I really appreciate the method provided by yours, I wanted to use your code as a comparative algorithm.I am using CUDA version 11.7 and cuDNN version 8.X. I encountered the following error

**Comment by sighdn** [comment]
Ok, thanks for the reply, I've fixed this issue
